--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kyleg/Pictures/wallpapers/zoe_cyberpop.jpg"

-- Special
background="#101317"
foreground="#caeaec"
cursor="#caeaec"

-- Colors
color0="#101317"
color1="#3860A4"
color2="#616997"
color3="#B36CBA"
color4="#699FB6"
color5="#AAA2BC"
color6="#A1A2D5"
color7="#caeaec"
color8="#8da3a5"
color9="#3860A4"
color10="#616997"
color11="#B36CBA"
color12="#699FB6"
color13="#AAA2BC"
color14="#A1A2D5"
color15="#caeaec"
