# Shell variables
# Generated by 'wal'
wallpaper='/home/kyleg/Pictures/wallpapers/zoe_cyberpop.jpg'

# Special
background='#101317'
foreground='#caeaec'
cursor='#caeaec'

# Colors
color0='#101317'
color1='#3860A4'
color2='#616997'
color3='#B36CBA'
color4='#699FB6'
color5='#AAA2BC'
color6='#A1A2D5'
color7='#caeaec'
color8='#8da3a5'
color9='#3860A4'
color10='#616997'
color11='#B36CBA'
color12='#699FB6'
color13='#AAA2BC'
color14='#A1A2D5'
color15='#caeaec'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
